# Generated by Django 4.2 on 2023-04-05 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='static/files/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('checking', 'Checking'), ('success', 'Success')], default='uploaded')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserFile',
                'verbose_name_plural': 'UserFiles',
            },
        ),
        migrations.CreateModel(
            name='FileLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.userfile')),
            ],
            options={
                'verbose_name': 'FileLog',
                'verbose_name_plural': 'FileLogs',
            },
        ),
    ]
